In [1]:
# bibliotecas usadas
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score 
from mpl_toolkits.mplot3d import Axes3D, axes3d
%matplotlib inline

In [2]:
# funcao normatiza dados
def Normatiza(x):
    strings=list(x)
    for i in strings:
        max_x=x[i].max()
        min_x=x[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=(x[i]-a)/b
    return x

In [3]:
# funcao retorna os dados a forma original
def Original(x,x_old):
    strings=list(x)
    for i in strings:
        max_x=x_old[i].max()
        min_x=x_old[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=x[i]*b+a
    return x

In [4]:
path="/home/ucfilho/Documents/Aulas/ANN_2018/Out_10_2018"
os.chdir(path)

In [5]:
DAT=pd.read_csv("Polimero_maio_21_2015.txt",sep='\t')
print(DAT.head())

   Time     TC     Y  MI    MW
0  80.0  170.0  76.5  62  2940
1  80.0  180.0  77.0  60  3470
2  90.0  170.0  78.0  66  3680
3  90.0  180.0  79.5  59  3890
4  85.0  175.0  79.9  72  3480


In [6]:
# separa as colunas de interesse
Index=range(5)
Dat_Select=[]
Dat_Select=DAT.iloc[:,Index].copy()

In [7]:
# separa os dados em normatizados e originais
DAT_OLD=[]
DAT_OLD=Dat_Select.copy()
DAT=Normatiza(Dat_Select)

In [8]:
# separa os dados em treino e teste
train=DAT.sample(frac=1.0,random_state=None) # poderia ser frac=0.5? sim ou nao?
test=DAT.drop(train.index)

In [9]:
# obtem as variaveis independentes (treino e teste)
x_train=train.iloc[:,[0,1]]
x_test=test.iloc[:,[0,1]]
X_OLD=DAT_OLD.iloc[:,[0,1]]

In [10]:
# obtem as variaveis dependentes (treino e teste)
Index=[2,3,4]
y_train=train.iloc[:,Index]
y_test=test.iloc[:,Index]
Y_OLD=DAT_OLD.iloc[:,Index]
print(Y_OLD)
print(x_train)

       Y  MI    MW
0   76.5  62  2940
1   77.0  60  3470
2   78.0  66  3680
3   79.5  59  3890
4   79.9  72  3480
5   80.3  69  3200
6   80.0  68  3410
7   79.7  70  3290
8   79.8  71  3500
9   78.4  68  3360
10  75.6  71  3020
11  78.5  58  3630
12  77.0  57  3150
        Time        TC
6   0.000000  0.000000
3   0.707214  0.707214
2   0.707214 -0.707214
8   0.000000  0.000000
1  -0.707214  0.707214
9   1.000000  0.000000
5   0.000000  0.000000
0  -0.707214 -0.707214
10 -1.000000  0.000000
4   0.000000  0.000000
7   0.000000  0.000000
11  0.000000  1.000000
12  0.000000 -1.000000


In [11]:
# define a rede neural 
clf = MLPRegressor(solver='lbfgs',activation='tanh',alpha=1e-5,hidden_layer_sizes=(6), 
                    random_state=1)

In [12]:
# treina a rede neural
clf.fit(x_train, y_train)

MLPRegressor(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=6, learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [13]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=clf.predict(x_train)
x_test=x_train
y_calc_test=clf.predict(x_test)
print(y_calc_train)
print(Y_OLD)

[[ 0.8475048   0.73143674 -0.08272757]
 [ 0.66080451 -0.73478589  0.99810392]
 [ 0.02334168  0.19987969  0.55741396]
 [ 0.8475048   0.73143674 -0.08272757]
 [-0.3999421  -0.61454025  0.10441758]
 [ 0.19005043  0.46902518 -0.11512356]
 [ 0.8475048   0.73143674 -0.08272757]
 [-0.61652874 -0.33401304 -1.00301002]
 [-0.99882037  0.87261699 -0.82788403]
 [ 0.8475048   0.73143674 -0.08272757]
 [ 0.8475048   0.73143674 -0.08272757]
 [ 0.23027157 -0.84968596  0.46428714]
 [-0.40422099 -0.99727988 -0.55640961]]
       Y  MI    MW
0   76.5  62  2940
1   77.0  60  3470
2   78.0  66  3680
3   79.5  59  3890
4   79.9  72  3480
5   80.3  69  3200
6   80.0  68  3410
7   79.7  70  3290
8   79.8  71  3500
9   78.4  68  3360
10  75.6  71  3020
11  78.5  58  3630
12  77.0  57  3150


In [14]:
# transforma a saida da rede em dataframe 
y_calc_train=pd.DataFrame(y_calc_train)
y_calc_test=pd.DataFrame(y_calc_test)
col_names=list(y_train)
y_calc_train.columns = col_names
y_calc_test.columns = col_names

In [15]:
# transforma dos dados calculados na forma original (nao normatizado)
y_calc_train=Original(y_calc_train,Y_OLD)
y_calc_test=Original(y_calc_test,Y_OLD)
print(y_calc_train)
print(Y_OLD)

            Y         MI           MW
0   79.941636  69.985776  3375.704402
1   79.502891  58.989106  3889.099363
2   78.004853  65.999098  3679.771632
3   79.941636  69.985776  3375.704402
4   77.010136  59.890948  3464.598351
5   78.396619  68.017689  3360.316307
6   79.941636  69.985776  3375.704402
7   76.501157  61.994902  2938.570239
8   75.602772  71.044627  3021.755086
9   79.941636  69.985776  3375.704402
10  79.941636  69.985776  3375.704402
11  78.491138  58.127355  3635.536393
12  77.000081  57.020401  3150.705434
       Y  MI    MW
0   76.5  62  2940
1   77.0  60  3470
2   78.0  66  3680
3   79.5  59  3890
4   79.9  72  3480
5   80.3  69  3200
6   80.0  68  3410
7   79.7  70  3290
8   79.8  71  3500
9   78.4  68  3360
10  75.6  71  3020
11  78.5  58  3630
12  77.0  57  3150


In [16]:
def MW_calc(x_test,Y_OLD,clf):
    y_calc_test=clf.predict(x_test)
    y_calc_test=Original(y_calc_test,Y_OLD)
    return y_calc_test['MW']
def MI_calc(x_test,Y_OLD,clf):
    y_calc_test=clf.predict(x_test)
    y_calc_test=Original(y_calc_test,Y_OLD)
    return y_calc_test['MI']
def Y_calc(x_test,Y_OLD,clf):
    y_calc_test=clf.predict(x_test)
    y_calc_test=Original(y_calc_test,Y_OLD)
    return y_calc_test['Y']

def Desirability(y,U,T,L):
    if y<L:
        d=0
    if (y>=L)&(y<=T):
        d=(y-L)/(T-L)
    if (y>=T)&(y<+U):
        d=(U-y)/(U-T)
    if (y>U):
        d=0
    return d

In [17]:
def function(x):
    Time=x[0]
    TC=x[1]
    MW=MW_calc(Time, TC)
    MI=MI_calc(Time, TC)
    Y=Y_calc(Time, TC)
    U=3890
    T=3400
    L=2940
    d1=Desirability(MW,U,T,L)
    U=68
    T=65
    L=62
    d2=Desirability(MI,U,T,L)
    U=80
    T=77.5
    L=75.6
    d3=Desirability(Y,U,T,L)
    fun = (-1)*(d1*d2*d3)**(1/3)
    return fun

In [18]:
x = np.linspace(-6, 6, 5)
y = np.linspace(-6, 6, 5)

X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[[-6. -3.  0.  3.  6.]
 [-6. -3.  0.  3.  6.]
 [-6. -3.  0.  3.  6.]
 [-6. -3.  0.  3.  6.]
 [-6. -3.  0.  3.  6.]]
[[-6. -6. -6. -6. -6.]
 [-3. -3. -3. -3. -3.]
 [ 0.  0.  0.  0.  0.]
 [ 3.  3.  3.  3.  3.]
 [ 6.  6.  6.  6.  6.]]


In [19]:
print("hello world,I am evolving!!!")

hello world,I am evolving!!!


PS: no planejamento de experimentos utilizando o Statistica -e-papers
Y=80
MI=65,044
MW=3586,1

tempo=86,65 e Temperatura=178,77