<a href="https://colab.research.google.com/github/ucfilho/ANN/blob/master/ANN_2022/Image_05/class_005_feature_extraction_image_006_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import numpy as np
import pandas as pd
import random
import zipfile
from matplotlib import pyplot as plt
import skimage.feature
from string import digits
import seaborn as sns
import skimage
import tensorflow as tf

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
!git clone https://github.com/ucfilho/Machine_Learning_DataSet
%cd Machine_Learning_DataSet

fatal: destination path 'Machine_Learning_DataSet' already exists and is not an empty directory.
/content/Machine_Learning_DataSet


In [ ]:
FILE='trash_features.zip'

In [ ]:
archive = zipfile.ZipFile(FILE, 'r')
archive.extractall()

In [ ]:
'''
flag = 0
with zipfile.ZipFile(FILE, "r") as f:
    for name in f.namelist():
        df = pd.read_excel(name)
        df = df.drop(['Unnamed: 0'], axis=1)
        print(df.head())
        flag = flag + 1
'''

'\nflag = 0\nwith zipfile.ZipFile(FILE, "r") as f:\n    for name in f.namelist():\n        df = pd.read_excel(name)\n        df = df.drop([\'Unnamed: 0\'], axis=1)\n        print(df.head())\n        flag = flag + 1\n'

In [ ]:
flag = 0
with zipfile.ZipFile(FILE, "r") as f:
    for name in f.namelist():
        if(flag == 0):
          df1 = pd.read_excel(name)
          df1 = df1.drop(['Unnamed: 0'], axis=1)
        else:
          df2 = pd.read_excel(name)
          df2 = df2.drop(['Unnamed: 0'], axis=1)
          df1[df2.columns]=df2
        flag = flag + 1

In [ ]:
pd.set_option('display.max_columns', None)
df1.head()

SRE      LRE      GLU       RLU    RPC  SRE_r    LRE_r    GLU_r  \
0  1.885  441.593  601.989  1005.119  7.326  1.862  536.232  664.287   
1  1.745  458.920  659.125   802.177  6.752  1.624  743.034  850.443   
2  2.103  382.622  565.440  1318.246  7.882  2.090  352.974  551.256   
3  2.034  273.901  501.999  1385.442  8.814  2.041  294.817  493.519   
4  1.698  623.255  781.935   621.709  5.609  1.739  681.119  788.395   

      RLU_r  RPC_r  SRE_g    LRE_g    GLU_g     RLU_g  RPC_g  SRE_b    LRE_b  \
0   896.815  6.665  1.746  659.323  766.338   687.234  5.794  1.782  580.653   
1   546.727  5.282  1.715  469.567  675.001   752.229  6.577  1.668  672.525   
2  1333.303  8.064  2.110  402.531  572.644  1312.092  7.785  2.109  252.945   
3  1424.571  8.982  2.042  262.164  490.380  1424.687  9.009  2.093  354.629   
4   645.759  5.563  1.749  445.448  658.773   788.733  6.644  1.706  619.011   

     GLU_b     RLU_b  RPC_b       0      1      2     3     4    5    6  7  \
0  737.706   742.000  6.034   98507  72820  20929     0  4352    0    0  0   
1  799.677   609.781  5.597  112047  49528  35033     0     0    0    0  0   
2  472.342  1589.454  9.362  128064  35953  27690   781  4120    0    0  0   
3  531.776  1379.448  8.323  110335  54333  19188  5999  5496  465  792  0   
4  773.733   637.034  5.679  111833  57103  27672     0     0    0    0  0   

        8      9     10    11    12    13    14  15      16     17     18  \
0   98715  73261  20308   179  4145     0     0   0   98224  73136  21219   
1  110941  51552  34115     0     0     0     0   0  112362  49358  34888   
2  122667  42130  24356   883  6572     0     0   0  127237  36762  27689   
3  108342  53490  17650  7008  7501  1025  1592   0  110300  54364  19220   
4  122947  46375  26150     0  1136     0     0   0  112167  57006  27435   

     19    20   21   22  23      24     25     26    27    28   29  30  31  \
0     0  4029    0    0   0  110805  60474  20202     0  5127    0   0   0   
1     0     0    0    0   0  111847  49488  35267     0     6    0   0   0   
2   768  4152    0    0   0  130756  32819  28654   834  3545    0   0   0   
3  6016  5472  448  788   0  112259  52506  21681  5739  4230  193   0   0   
4     0     0    0    0   0  109556  59115  27937     0     0    0   0   0   

     contrast  dissimilarity  homogeneity    energy  correlation       ASM  \
0  498.964103       9.867628     0.238681  0.029830     0.948122  0.000890   
1  356.344391      11.277083     0.178445  0.027051     0.991291  0.000732   
2  834.724359      12.536218     0.247208  0.028026     0.875504  0.000785   
3  854.156250      13.713301     0.399496  0.043164     0.899442  0.001863   
4  194.098718       9.643910     0.158241  0.024129     0.984573  0.000582   

   contrast_r  dissimilarity_r  homogeneity_r  energy_r  correlation_r  \
0  590.412821        11.158333       0.206623  0.029813       0.946295   
1  378.684455        11.681891       0.174064  0.026368       0.990881   
2  609.068109        11.054968       0.245956  0.028595       0.844251   
3  892.051923        15.163782       0.370711  0.037676       0.878187   
4  194.019071         9.525801       0.158687  0.026792       0.984622   

      ASM_r  contrast_g  dissimilarity_g  homogeneity_g  energy_g  \
0  0.000889  521.523077        10.183654       0.232813  0.030270   
1  0.000695  354.198878        11.272596       0.177230  0.027354   
2  0.000818  801.410897        12.308013       0.247567  0.028183   
3  0.001419  862.706090        13.791987       0.392301  0.041822   
4  0.000718  193.937019         9.581571       0.156499  0.024323   

   correlation_g     ASM_g   contrast_b  dissimilarity_b  homogeneity_b  \
0       0.947509  0.000916   447.287660         9.174840       0.254093   
1       0.991109  0.000748   343.230128        11.041346       0.178819   
2       0.871604  0.000794  1018.333974        13.876923       0.237472   
3       0.900380  0.001749   865.250000        13.726603     

In [ ]:
img_name = df1['name'].values

tipos = []
selected = 'find'
for x in img_name:
  result =''.join([i for i in x[:-4] if not i.isdigit()])
  if(result != selected):
    selected = result
    tipos.append(selected)

In [ ]:
tipos

['cardboard', 'glass', 'metal', 'paper', 'plastic', 'trash']

In [ ]:
y=df1['class']
X=df1.drop(['name','class'], axis='columns')

In [ ]:
y = pd.get_dummies(y)
# check https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html
y

0  1  2  3  4  5
0     1  0  0  0  0  0
1     1  0  0  0  0  0
2     1  0  0  0  0  0
3     1  0  0  0  0  0
4     1  0  0  0  0  0
...  .. .. .. .. .. ..
2522  0  0  0  0  0  1
2523  0  0  0  0  0  1
2524  0  0  0  0  0  1
2525  0  0  0  0  0  1
2526  0  0  0  0  0  1

[2527 rows x 6 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, stratify=y, random_state=1)

In [ ]:
scaler = StandardScaler()
# transform data
scaler_X = scaler.fit(X_train)
X_train = scaler_X.transform(X_train)
X_test = scaler_X.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,


In [ ]:
nin = X_train.shape[1]
nout =y.shape[1]
nhidden = 50

In [ ]:
# Create a `Sequential` model and add a Dense layer as the first layer.
model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(nin,)))
model.add(tf.keras.layers.Dense(nhidden, activation='relu'))
# Now the model will take as input arrays of shape (None, 16)
# and output arrays of shape (None, 32).
# Note that after the first layer, you don't need to specify
# the size of the input anymore:
model.add(tf.keras.layers.Dense(nout, activation='softmax'))

In [ ]:
X_test = np.array(X_test )
y_test = np.array(y_test)
y_test = y_test.astype(np.int32)
y_train = y_train.astype(np.int32)
X_train = X_train.reshape(-1, nin) 
X_test = X_test.reshape(-1, nin)

In [ ]:
model.compile(
  loss='categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy']
)

In [ ]:
# gives us back a <keras.callbacks.History object at 0x112e61a90>
#r = model.fit(X_train, y_train, validation_data = (X_test,y_test), epochs=15, batch_size=32)
r = model.fit(X_train, y_train, epochs=100)
print("Returned:", r)

Epoch 1/100
53/53 [==============================] - 2s 6ms/step - loss: 1.7055 - accuracy: 0.3136
Epoch 2/100
53/53 [==============================] - 0s 5ms/step - loss: 1.3777 - accuracy: 0.4861
Epoch 3/100
53/53 [==============================] - 0s 5ms/step - loss: 1.2643 - accuracy: 0.5204
Epoch 4/100
53/53 [==============================] - 0s 5ms/step - loss: 1.1911 - accuracy: 0.5558
Epoch 5/100
53/53 [==============================] - 0s 3ms/step - loss: 1.1399 - accuracy: 0.5824
Epoch 6/100
53/53 [==============================] - 0s 3ms/step - loss: 1.0985 - accuracy: 0.5901
Epoch 7/100
53/53 [==============================] - 0s 5ms/step - loss: 1.0651 - accuracy: 0.6072
Epoch 8/100
53/53 [==============================] - 0s 3ms/step - loss: 1.0361 - accuracy: 0.6214
Epoch 9/100
53/53 [==============================] - 0s 4ms/step - loss: 1.0106 - accuracy: 0.6261
Epoch 10/100
53/53 [==============================] - 0s 2ms/step - loss: 0.9903 - accuracy: 0.6415
Epoch 11/

In [ ]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=model.predict(X_train)
y_calc_test=model.predict(X_test)

27/27 [==============================] - 0s 1ms/step


In [ ]:
y_calc_test

array([[9.8936208e-02, 5.5160015e-03, 1.7389989e-03, 8.5630172e-01,
        1.7400818e-02, 2.0106297e-02],
       [1.6207052e-02, 9.5721886e-02, 3.5911824e-03, 7.7058762e-01,
        1.0842923e-01, 5.4631145e-03],
       [2.6256829e-03, 5.7983130e-02, 1.4245290e-02, 4.9558546e-02,
        8.7465400e-01, 9.3333743e-04],
       ...,
       [1.5674429e-02, 2.0316535e-01, 4.3870589e-01, 4.1163363e-04,
        1.4203860e-01, 2.0000401e-01],
       [3.5527037e-04, 2.3263819e-04, 1.7984945e-04, 9.9856454e-01,
        7.4491909e-05, 5.9319963e-04],
       [6.7849383e-02, 4.3822157e-01, 5.6828945e-03, 3.4718871e-01,
        1.3323288e-01, 7.8246519e-03]], dtype=float32)

In [ ]:
def retorna(y):
  resp = []
  for yi in y:
    vmax =max(yi)
    for idx, x in enumerate(yi):
      if(x == vmax):
        resp.append(idx)
  return resp

In [ ]:
y_test[0]

array([0, 0, 0, 0, 1, 0], dtype=int32)

In [ ]:
y_calc = retorna(y_calc_test)
y_test = retorna(y_test)

In [ ]:
confusion_matrix(y_test, y_calc)

array([[ 99,   9,   4,  16,   2,   3],
       [  2, 100,  23,  10,  24,   7],
       [  4,  28,  77,  11,  11,   4],
       [ 11,   7,   8, 150,  19,   1],
       [  0,  28,  11,  15, 103,   2],
       [  1,   5,   6,   1,  10,  22]])

In [ ]:
# Classification Report
print('\n\n', classification_report(y_test, y_calc, target_names=tipos))



               precision    recall  f1-score   support

   cardboard       0.85      0.74      0.79       133
       glass       0.56      0.60      0.58       166
       metal       0.60      0.57      0.58       135
       paper       0.74      0.77      0.75       196
     plastic       0.61      0.65      0.63       159
       trash       0.56      0.49      0.52        45

    accuracy                           0.66       834
   macro avg       0.65      0.64      0.64       834
weighted avg       0.66      0.66      0.66       834

